from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import get_settings
from app.database import Base, engine
from app.routers import estimate, foods

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    description=(
        "Backend for the Indian Food Nutrition Estimator. Vision AI recognizes food; "
        "nutrient values are always retrieved from the IFCT-based database via RAG, "
        "never generated by the model."
    ),
    version="0.1.0",
)

# Open CORS for development so the separately-built frontend can call this
# API from any origin (mobile dev servers, Expo, etc.) without friction.
# Tighten this to specific origins before any production deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(estimate.router, prefix=settings.api_v1_prefix)
app.include_router(foods.router, prefix=settings.api_v1_prefix)


@app.on_event("startup")
def on_startup():
    Base.metadata.create_all(bind=engine)


@app.get("/health")
def health():
    return {"status": "ok", "app": settings.app_name}
